### ISSUE TITLE
ShadowHand grasp generation for objects on the table

### ISSUE THREAD

**Issue by liuallen871219** [PKU-EPIC/DexGraspNet#1]
For table-top grasping generation, it seem need information about object pose(../data/pose). 
What is the format of this file?

Best regards,
Allen

**Comment by mzhmxzh** [comment]
Thank you for your comment. 

For table-top generation, every object is supposed to have a `data/poses/object_code.npy` file to record transformations from the object reference frame (where the object is zero-centered and normalized) to the world reference frame (where the object lies stably on the top of the table, which coincides with the `z=0` plane). 

Each file is a list of `4x4` homogeneous transformation matrices, generated by running `python grasp_generation/scripts/generate_object_pose.py`, which raises each object to a random height above the table, rotates it randomly, then drops it onto the table in a free-fall. This process is repeated `--n_samples` times to collect diverse poses. We choose SAPIEN as the physics simulator that does this simulation. 

We updated the `grasp_generation/README.md` file of the  `table` branch, added comments and doc strings in the source code, and included some sample data upon your comment. 

We are happy to provide further clarifications. 
Jialiang Zhang

**Comment by liuallen871219** [comment]
Thanks!!

**Comment by kaijieshi7** [comment]
Hi. Thanks for the great work. Can I know the version of SAPIEN package?

**Comment by wetoo-cando** [comment]
```
[SAPIEN] [critical] Missing required child <mass>
...
RuntimeError: Missing required child
```

Seems like sapien is looking for a "mass" attribute in the URDF file, but there is none. 

Is this attribute important for DexGraspNet? If not, how can I get around this?

**Comment by wetoo-cando** [comment]
Downgrading to sapien 1.1.1 works.
