### ISSUE TITLE
create mano+object meshes

### ISSUE THREAD

**Issue by anilesec** [PKU-EPIC/DexGraspNet#11]
Dear @mzhmxzh @wrc042 

Thanks for awesome work.
Is it possible to generate MANO grasps for all 1.32M grasps?  
Could you please provide an example to generate MANO grasp?

Thanks in Advance!

**Comment by mzhmxzh** [comment]
Yes, you can use the [mano](https://github.com/PKU-EPIC/DexGraspNet/tree/mano) branch or the [mano-table](https://github.com/PKU-EPIC/DexGraspNet/tree/mano-table) branch. 

The mano branch includes an implementation of DexGraspNet for the MANO hand. We also provide pre-generated examples and visualization scripts in that branch. 

The mano-table branch is used to generate MANO grasps for objects on a table. It has an additional energy term to penalize the penetration between the MANO and the table. 

All the hyper parameters are properly tuned, and you can use the same objects in the Shadow Hand dataset. All you need to do is prepare enough gpus and run the scripts. :)
