### ISSUE TITLE
Questions about data errors in the dataset

### ISSUE THREAD

**Issue by hooyahliu** [PKU-EPIC/DexGraspNet#12]
Hello, 
I downloaded the DexGraspNet dataset and used Open3D to visualize it.
I found that the grasping poses in the dataset did not make good contact with the object. Is this normal?
Some sample pictures are as follows:
![image](https://github.com/PKU-EPIC/DexGraspNet/assets/16132238/7d8b2ac8-a06d-4feb-ac7d-2267a0e83321)
![image](https://github.com/PKU-EPIC/DexGraspNet/assets/16132238/a2d46917-bf94-48c4-b726-7a79e22389cc)

**Comment by mzhmxzh** [comment]
Try `pip install trimesh==3.10`.

**Comment by hooyahliu** [comment]
> Try `pip install trimesh==3.10`.

thank you for your reply. I also used the [quick_example.ipynb](https://github.com/PKU-EPIC/DexGraspNet/blob/main/grasp_generation/quick_example.ipynb) and trimesh, to visualize some data, and this problem still exists.

![image](https://github.com/PKU-EPIC/DexGraspNet/assets/16132238/ed845bde-4b8e-46c7-ab33-0e7e15551b14)
![image](https://github.com/PKU-EPIC/DexGraspNet/assets/16132238/9bd6132c-68f0-492a-a115-d20b6efd897e)
![image](https://github.com/PKU-EPIC/DexGraspNet/assets/16132238/f1f33a65-e0f7-428b-bca4-af3f5128cd18)

**Comment by mzhmxzh** [comment]
Your trimesh's version is too high, try downgrading it to 3.10. 
The reasons are explained [here](https://github.com/PKU-EPIC/DexGraspNet/issues/8#issuecomment-1801937535).
