### ISSUE TITLE
what is from isaacgymenvs import gymapi in isaac_validator.py

### ISSUE THREAD

**Issue by zoctipus** [PKU-EPIC/DexGraspNet#14]
When I run validate_grasps.py,

I get import `error: Module not found from isaacgymenvs import gymapi `

installling isaacgymenvs is not mentioned in the documentation, (only isaac gym), 
So I go ahead and downloaded isaacgymenvs from [IsaacGymEnvs](https://github.com/NVIDIA-Omniverse/IsaacGymEnvs) and `pip install -e . ` it

However gymapi is also not a submodule in isaacgymenvs. So is this isaacgymenvs just isaacgym?

**Comment by wukongwong** [comment]
Can this repo work in 4090GPU. I have all kinds of problems with configuring this environment.

**Comment by wukongwong** [comment]
> Yes, I remember that you only need to install isaacgym. No addtional installation for gymapi.

Can this repo work in 4090GPU. I have all kinds of problems with configuring this environment.
