### ISSUE TITLE
ValueError: exactly one among 'object_code_list' 'all' should be specified

### ISSUE THREAD

**Issue by Charlie0257** [PKU-EPIC/DexGraspNet#2]
When I run the command `python scripts/generate_grasps.py`, there is an error occurs——

Traceback (most recent call last):
  File "scripts/generate_grasps.py", line 213, in <module>
    raise ValueError('exactly one among \'object_code_list\' \'all\' should be specified')

Thanks for any help :)

**Comment by mzhmxzh** [comment]
Try running the script with command `cd grasp_generation; CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python scripts/generate_grasps.py --all`. This will generate grasps for all objects in `data/meshdata`. 

If you want to specify a list of objects, try `cd grasp_generation; CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python scripts/generate_grasps.py --object_code_list object_code_1 object_code_2 object_code_3`. 

Furthermore, you can specify a todo list `todo.txt` and inform the script by setting the flag `--todo`. 

We will clarify this in the comments of the script soon.

**Comment by Charlie0257** [comment]
Thanks for your replying! I can run the command `python scripts/generate_grasps.py --all` now :)

However, when I try to validate the result `python scripts/validate_grasps.py`, there is an error occurs——
Traceback (most recent call last):
  File "scripts/validate_grasps.py", line 74, in <module>
    hand_model = HandModel(
TypeError: __init__() missing 2 required positional arguments: 'contact_points_path' and 'penetration_points_path'

Could you offer a detailed demo commend to tell me how to input the correct parameters for this command?

Thanks :) @mzhmxzh

**Comment by mzhmxzh** [comment]
There seems to be a bug with code consistency. It should be fine now. You can run the command `cd grasp_generation; python scripts/validate_grasps.py` in the newest commit. Thank you for pointing this out! :)

**Comment by Charlie0257** [comment]
Thanks for your help :)
However, there is another error occurs when running `python scripts/validate_grasps.py`——

Traceback (most recent call last):
  File "scripts/validate_grasps.py", line 150, in <module>
    E_pen_array.append(data_dict[i]["E_pen"])
KeyError: 'E_pen'

Could you give me some help? @mzhmxzh

**Comment by Charlie0257** [comment]
Thanks for your patient answers :) All codes are currently working fine!

I am curious if it is possible to visualize the effect of validation in isaacgym during the validation phase when I run `python scripts/validate_grasps.py`?

**Comment by wrc042** [comment]
You can turn on a GUI window of Isaac Gym by adding an argument, `python scripts/validate_grasps.py --index 0`. This will display the object you specified. If you want to watch multiple objects in a window, I think you can modify our script to do so.

**Comment by Charlie0257** [comment]
Thanks :)
