### ISSUE TITLE
MIssing file visualize_data_table_top.py

### ISSUE THREAD

**Issue by liuallen871219** [PKU-EPIC/DexGraspNet#3]
I want to show the table-top grasp. I follow the instruction to generate grasping pose but I can not find the file  **visualize_data_table_top.py**
Another question is Can I use the same file(validate_grasps.py) from the main branch to validate table-top grasp in issacsim ?

**Comment by liuallen871219** [comment]
Thanks for your reply!!
I have another problem that I want to generate tabletop mano hand grasp. Can you give me some advice that how to modify your implementation

Best regards

**Comment by mzhmxzh** [comment]
Four modifications are needed: 
1. Use `grasp_generation/scripts/generate_object_pose.py` from branch `table` to drop objects onto the table. 
2. Implement an initialization function to initialize MANO hands above the table plane, following `grasp_generation/utils/initializations.py` from branch `table`. 
3. Add an energy term to penalize any MANO vertex that penetrates the table plane. A possible choice could be $E_{\text{tpen}} = \sum_{p\in V(H)}\max (0, -p_z)  $, where $V(H)$ represents the 778 MANO vertices in the table reference frame (so the `z` coordinate shows the height above the table). This can be achieved by implementing a `cal_dis_plane` method for class `HandModel`, and use this method to compute `E_tpen` in `energy.py`, as in branch `table`. 
4. Modify `main.py` to record `E_pen`. 

We are writing a more detailed instruction in the README files of branches `mano` and `table`, and will also provide a complete implementation for table-top MANO grasp generation soon. You can try your own implementations for the MANO version of `E_tpen`, too. :)

**Comment by mzhmxzh** [comment]
We created a new branch `mano-table`. It contains a complete pipeline that can generate grasps for MANO on top of a table, and some pre-computed examples in `data` which can be visualized by running `visualize_result.py`. 

We will update the README files soon.

**Comment by liuallen871219** [comment]
I have another question. Is it also possible to validate the generated mano table-top grasp in Isaac?

**Comment by wrc042** [comment]
We have not yet attempted validation of the Mano hand in Isaac, as its implementation would require significant modifications, since the Mano hand cannot be modeled as articulated rigid bodies as the ShadowHand. I may not be able to provide you much help. However, I would suggest exploring whether Isaac offers official tools that support Mano hand simulation or if you could import it as fixed rigid bodies. Be aware that the simulator may automatically operate convex decomposition. Best of luck with your project.
