### ISSUE TITLE
WRJTx, WRJTy, WRJTz, WRJRx, WRJRy, WRJRz are for which link and which coordinate system

### ISSUE THREAD

**Issue by oxidationreduction** [PKU-EPIC/DexGraspNet#5]
Hi.

I am trying to visualize the result of your outstanding model to a simulator (Sapien), which needs to load the object and the hand to a new virtual environment. I am wondering the following 6 parameters `WRJTx, WRJTy, WRJTz, WRJRx, WRJRy, WRJRz` are for which link and coordinate system. I thought they were of the `palm_link`'s pose recorded in the global coordinate system but when I applied the params to the hand, the visualization result was strange.

Could you tell me those 6 params are recorded in which coordinate system, and whether they are params for the `palm_link`? Thank you.

I am using Allegro Hand and the object names `core-jar-e93934fc1da4635d5aa09a1176194412`. I transferred `WRJRx, WRJRy, WRJRz` to quaternion using `transforms3d.euler.euler2quat(qpos['WRJRx'], qpos['WRJRy'], qpos['WRJRz'], 'sxyz')`.

**Comment by mzhmxzh** [comment]
These parameters describe the `base_link`'s pose in the object's coordinate system. If the object is at the origin of the world coordinate system, then it should also describe the `base_link`'s pose in the world coordinate system. The rotation is recorded in Euler angles (`sxyz` format). So I think your understanding is correct. 
I cannot guess why SAPIEN does not visualize the data correctly, but you can try [this script](https://github.com/PKU-EPIC/DexGraspNet/blob/allegro/grasp_generation/tests/visualize_result.py) to visualize it in Plotly.

**Comment by oxidationreduction** [comment]
Thank you. There is a virtual link called `world` in the hand's URDF and `base_link` is not aligned with it. I made `base_link` place at the world's origin and everything works smoothly both in SAPIEN and Plotly now.
